[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"

# tailwind cli binary
command_arguments = ["-c", "tailwindcss -i src/tailwind.css -o $TRUNK_STAGING_DIR/main.css"]
